apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-volume
  namespace: ns-dev
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "git@github.com:maheswargoud/dev.git"