apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: PersistentVolumeClaim
  namespace: ns-dev
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 3Gi